services:
  - type: web
    name: ctp-platanar
    env: node
    plan: starter
    buildCommand: |
      cd ctp-platanar-frontend && npm install && npm run build && cd ../ctp-platanar-backend && npm install
    startCommand: cd ctp-platanar-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generator: secret
      - key: REACT_APP_API_URL
        value: /api
